---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform

  vars:
    project_dir: /test1/work1

  tasks:

   - name: Basic deploy of an instance
     cloud.terraform.terraform:
      project_path: '{{ project_dir }}'
      state: present
      force_init: true

   - name: Remove Instance
     cloud.terraform.terraform:
      project_path: '{{ project_dir }}'
      state: absent
      force_init: true
     tags:
       - never
       - remove
